# Generated by Django 2.2.3 on 2019-07-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_paragraph_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
